### ISSUE TITLE
bower: command not found

### ISSUE THREAD

**Issue by tratnayake** [bitnami/bitnami-docker-express#113]
**Description**

Running a `docker-compose up` with a `docker-compose.yml` (included at the bottom) which has `SKIP_BOWER_INSTALL` set to 0 gets 

```
INFO  ==> Installing bower packages.
webserver_1      | /opt/bitnami/express/functions: line 140: bower: command not found
<REDACTED>_webserver_1 exited with code 127
```

**Steps to reproduce the issue:**

1. `docker-compose up`
**Describe the results you received:**

(only included the relevant output from `webserver_1`)
```
webserver_1      |
webserver_1      | Welcome to the Bitnami express container
webserver_1      | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-express
webserver_1      | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-express/issues
webserver_1      |
webserver_1      | INFO  ==> Skipping creation of new application. Already exists!
webserver_1      | INFO  ==> Installing npm packages.
INFO  ==> Installing bower packages.
webserver_1      | /opt/bitnami/express/functions: line 140: bower: command not found
<REDACTED>_webserver_1 exited with code 127
```

**Describe the results you expected:**

The express server to star tup.

**Additional information you deem important (e.g. issue happens only occasionally):**

 

Have also tried with versions:
* latest
* 4-ol-7
* 4.16.4-ol-7-r115

**Version**

- Output of `docker version`:

```
docker version
Client: Docker Engine - Community
 Version:           18.09.1
 API version:       1.39
 Go version:        go1.10.6
 Git commit:        4c52b90
 Built:             Wed Jan  9 19:33:12 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.1
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       4c52b90
  Built:            Wed Jan  9 19:41:49 2019
  OS/Arch:          linux/amd64
  Experimental:     true
```

- Output of `docker info`:

```
docker version
Client: Docker Engine - Community
 Version:           18.09.1
 API version:       1.39
 Go version:        go1.10.6
 Git commit:        4c52b90
 Built:             Wed Jan  9 19:33:12 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.1
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       4c52b90
  Built:            Wed Jan  9 19:41:49 2019
  OS/Arch:          linux/amd64
  Experimental:     true
 tratnaya  ~  docker info
Containers: 17
 Running: 0
 Paused: 0
 Stopped: 17
Images: 113
Server Version: 18.09.1
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9754871865f7fe2f4e74d43e2fc7ccd237edcbce
runc version: 96ec2177ae841256168fcf76954f7177af9446eb
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.125-linuxkit
Operating System: Docker for Mac
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.952GiB
Name: linuxkit-025000000001
ID: 4MF3:57KU:FHTP:MH7Q:RVWD:3DLL:2MYF:YHN3:XDAG:QRHI:YDCH:IH3U
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 27
 Goroutines: 54
 System Time: 2019-02-06T21:42:23.3351475Z
 EventsListeners: 2
HTTP Proxy: gateway.docker.internal:3128
HTTPS Proxy: gateway.docker.internal:3129
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version
docker-compose version 1.23.2, build 1110ad01
docker-py version: 3.6.0
CPython version: 3.6.6
OpenSSL version: OpenSSL 1.1.0h  27 Mar 2018
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

`docker-compose.yml`

```
# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_PASSWORD}
  webserver:
    tty: true # Enables debugging capabilities when attached to this container.
    image: 'bitnami/express:latest'
    labels:
      kompose.service.type: nodeport
    command: npm start
    environment:
      - DB_USER=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}        
      - PORT=3000
      - NODE_ENV=productions
      - DATABASE_URL=mongo://mongo:27017/<REDACTED>

      - SKIP_DB_WAIT=0
      - SKIP_DB_MIGRATION=0
      - SKIP_NPM_INSTALL=0
      - SKIP_BOWER_INSTALL=0
    depends_on:
      - mongo
    ports:
      - 3000:3000
    volumes:
      - ./app:/app    
```
